"""ChatMessage model update - human and ai message in same object

Revision ID: 4eafa02ca717
Revises: bfdbeedc66d5
Create Date: 2025-07-31 07:11:32.299451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eafa02ca717'
down_revision: Union[str, None] = 'bfdbeedc66d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('human_message', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('ai_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('positive_feedback', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('negative_feedback', sa.Boolean(), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('negative_feedback')
        batch_op.drop_column('positive_feedback')
        batch_op.drop_column('ai_message')
        batch_op.drop_column('human_message')

    # ### end Alembic commands ###
