"""JSON fields removed from ChatMessage model

Revision ID: bfdbeedc66d5
Revises: 68901a9ce043
Create Date: 2025-07-28 07:01:14.621621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bfdbeedc66d5'
down_revision: Union[str, None] = '68901a9ce043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('duration', sa.Double(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('chat_metadata')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_metadata', sqlite.JSON(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
        batch_op.drop_column('duration')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
